#!/usr/bin/env node

/**
 * convert-tokens.js
 *
 * Reads the colour and typography JSON token files from `tokens/`,
 * resolves colour-role references (e.g. "{color.palette.primary.80}")
 * against the primitive palette, and writes a single CSS file containing
 * all design tokens as CSS custom properties.
 *
 * Colour roles are output for both light (`:root`) and dark
 * (`[data-theme="dark"]`) themes. Primitive palette values are NOT
 * exposed as CSS variables — only the role-level tokens are, as the
 * UI should consume roles exclusively.
 *
 * Usage:
 *   node scripts/convert-tokens.js
 */

const fs = require('fs');
const path = require('path');

// ── Paths ──────────────────────────────────────────────────────────
const TOKENS_DIR = path.resolve(__dirname, '..', 'tokens');
const COLOUR_FILE = path.join(TOKENS_DIR, 'colour-tokens.json');
const TYPO_FILE = path.join(TOKENS_DIR, 'typography-tokens.json');
const OUTPUT_FILE = path.join(TOKENS_DIR, 'design-tokens.css');

// ── Helpers ────────────────────────────────────────────────────────

/**
 * Convert a camelCase or PascalCase string to kebab-case.
 * e.g. "onPrimaryContainer" → "on-primary-container"
 */
function toKebab(str) {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

/**
 * Parse an HSL string like "hsl(218, 100%, 50%)" into { h, s, l } numbers.
 */
function parseHSL(hslStr) {
  const m = hslStr.match(/hsl\(\s*([\d.]+)\s*,\s*([\d.]+)%?\s*,\s*([\d.]+)%?\s*\)/i);
  if (!m) return null;
  return { h: parseFloat(m[1]), s: parseFloat(m[2]), l: parseFloat(m[3]) };
}

/**
 * Linearly interpolate between two numbers.
 */
function lerp(a, b, t) {
  return a + (b - a) * t;
}

/**
 * Given a palette object (e.g. { "0": "hsl(…)", "10": "hsl(…)", … }) and a
 * target tonal stop that doesn't exist in the object, interpolate the HSL
 * value from the two nearest existing stops.
 *
 * Returns an HSL string or `null` if interpolation isn't possible.
 */
function interpolatePaletteTone(paletteObj, targetTone) {
  const stops = Object.keys(paletteObj)
    .map(Number)
    .filter((n) => !isNaN(n))
    .sort((a, b) => a - b);

  // Find the two surrounding stops
  let lower = null;
  let upper = null;
  for (let i = 0; i < stops.length; i++) {
    if (stops[i] <= targetTone) lower = stops[i];
    if (stops[i] >= targetTone && upper === null) upper = stops[i];
  }

  if (lower === null || upper === null) return null;
  if (lower === upper) return paletteObj[String(lower)];

  const lowerHSL = parseHSL(paletteObj[String(lower)]);
  const upperHSL = parseHSL(paletteObj[String(upper)]);
  if (!lowerHSL || !upperHSL) return null;

  const t = (targetTone - lower) / (upper - lower);
  const h = Math.round(lerp(lowerHSL.h, upperHSL.h, t));
  const s = Math.round(lerp(lowerHSL.s, upperHSL.s, t) * 10) / 10;
  const l = Math.round(lerp(lowerHSL.l, upperHSL.l, t) * 10) / 10;

  return `hsl(${h}, ${s}%, ${l}%)`;
}

/**
 * Resolve a token reference string like "{color.palette.primary.80}"
 * or "{color.key.primary}" against the full colour data object.
 *
 * For palette references where the exact tonal stop doesn't exist,
 * the function interpolates between the nearest available stops.
 *
 * Returns the resolved HSL value, or `null` if the path can't be found.
 */
function resolveRef(ref, colourData) {
  // Strip the curly braces → "color.palette.primary.80"
  const tokenPath = ref.replace(/^\{|\}$/g, '');
  const segments = tokenPath.split('.');

  let current = colourData;
  for (const seg of segments) {
    if (current == null || typeof current !== 'object') return null;

    // Try exact key first, then case-insensitive fallback
    if (seg in current) {
      current = current[seg];
    } else {
      const lower = seg.toLowerCase();
      const match = Object.keys(current).find((k) => k.toLowerCase() === lower);
      if (match) {
        current = current[match];
      } else {
        // If this is the last segment and the parent looks like a palette
        // (keys are numeric tonal stops), try to interpolate.
        const tone = parseFloat(seg);
        if (!isNaN(tone) && seg === segments[segments.length - 1]) {
          return interpolatePaletteTone(current, tone);
        }
        return null;
      }
    }
  }

  return typeof current === 'string' ? current : null;
}

// ── Main ───────────────────────────────────────────────────────────

function main() {
  // 1. Read source files
  const colourData = JSON.parse(fs.readFileSync(COLOUR_FILE, 'utf-8'));
  const typoData = JSON.parse(fs.readFileSync(TYPO_FILE, 'utf-8'));

  // 2. Build the output CSS lines
  const lines = [];

  lines.push('/* ============================================================');
  lines.push('   Design Tokens — auto-generated by scripts/convert-tokens.js');
  lines.push('   DO NOT EDIT BY HAND — re-run the script after updating the');
  lines.push('   source JSON files in tokens/.');
  lines.push('   ============================================================ */');
  lines.push('');

  // ── 2a. Typography tokens (theme-agnostic → :root) ──────────────
  lines.push('/* ---------- Typography ---------- */');
  lines.push(':root {');

  const typo = typoData.typography;
  for (const [key, value] of Object.entries(typo)) {
    // Keys are already kebab-case in the JSON, but normalise just in case
    const varName = `--${toKebab(key)}`;
    const cssValue = typeof value === 'number' ? value : `${value}`;
    lines.push(`  ${varName}: ${cssValue};`);
  }

  lines.push('}');
  lines.push('');

  // ── 2b. Colour role tokens — light theme (:root) ───────────────
  const roles = colourData.color?.role;
  if (!roles) {
    console.error('ERROR: "color.role" not found in colour-tokens.json');
    process.exit(1);
  }

  // Helper: emit a block of colour role variables
  function emitRoleBlock(selector, roleMap, label) {
    lines.push(`/* ---------- Colour Roles (${label}) ---------- */`);
    lines.push(`${selector} {`);

    const warnings = [];

    for (const [roleName, ref] of Object.entries(roleMap)) {
      const varName = `--color-${toKebab(roleName)}`;

      if (typeof ref === 'string' && ref.startsWith('{')) {
        const resolved = resolveRef(ref, colourData);
        if (resolved) {
          lines.push(`  ${varName}: ${resolved};`);
        } else {
          warnings.push(`  ⚠  Could not resolve "${ref}" for role "${roleName}"`);
          lines.push(`  /* UNRESOLVED: ${ref} */`);
          lines.push(`  ${varName}: transparent;`);
        }
      } else {
        // Direct value (shouldn't happen, but handle it)
        lines.push(`  ${varName}: ${ref};`);
      }
    }

    lines.push('}');
    lines.push('');

    if (warnings.length) {
      console.warn(`\nWarnings for ${label} roles:`);
      warnings.forEach((w) => console.warn(w));
    }
  }

  if (roles.light) {
    emitRoleBlock(':root', roles.light, 'Light');
  }

  if (roles.dark) {
    emitRoleBlock('[data-theme="dark"]', roles.dark, 'Dark');
  }

  // 3. Write CSS
  const css = lines.join('\n') + '\n';
  fs.writeFileSync(OUTPUT_FILE, css, 'utf-8');

  console.log(`\n✅  Design tokens written to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  console.log(`    • Typography variables: ${Object.keys(typo).length}`);
  console.log(
    `    • Light colour role variables: ${roles.light ? Object.keys(roles.light).length : 0}`
  );
  console.log(
    `    • Dark colour role variables: ${roles.dark ? Object.keys(roles.dark).length : 0}`
  );
}

main();
